name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile=false

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: API Tests
        run: pnpm --filter @construction/api test -- --test-reporter=spec

      - name: Install Playwright Browsers
        run: pnpm --filter @construction/web exec npx playwright install --with-deps

      - name: Start API
        run: pnpm --filter @construction/api start &
        env:
          PORT: 3000

      - name: Wait for API
        run: npx -y wait-on http://localhost:3000/health

      - name: Start Web
        run: pnpm --filter @construction/web dev &
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3000
        timeout-minutes: 1

      - name: Wait for Web
        run: npx -y wait-on http://localhost:3001

      - name: Web E2E
        run: pnpm --filter @construction/web e2e
        env:
          WEB_BASE_URL: http://localhost:3001